-keep class com.badlogic.gdx.** { *; }
-keep class game.** { *; }
-dontwarn com.badlogic.gdx.**
-keepclassmembers class game.level.** { *; }
-keep class com.google.gson.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
